steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/crm-project-412707/crm-project-3tier:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/crm-project-412707/crm-project-3tier:$SHORT_SHA']
