steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/crm-project-412707/crm-project-3tier:208b4d6', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/crm-project-412707/crm-project-3tier:208b4d6']
