version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
